CREATE TABLE PESSOA (
    ID BIGSERIAL NOT NULL,
    NOME CHARACTER VARYING(100) NOT NULL,
    DATANASCIMENTO DATE, 
    CPF CHARACTER VARYING(14),
    FUNCIONARIO BOOLEAN, 
    CONSTRAINT PK_PESSOA PRIMARY KEY (ID)
);

CREATE TABLE PROJETO (
    ID BIGSERIAL NOT NULL,
    NOME VARCHAR(200) NOT NULL,
    DATA_INICIO DATE,
    DATA_PREVISAO_FIM DATE,
    DATA_FIM DATE,
    DESCRICAO VARCHAR(5000),
    STATUS VARCHAR(45),
    ORCAMENTO FLOAT,
    RISCO VARCHAR(45),
    IDGERENTE BIGSERIAL NOT NULL,
    CONSTRAINT PK_PROJETO PRIMARY KEY (ID),
    CONSTRAINT FK_GERENTE FOREIGN KEY (IDGERENTE) REFERENCES PESSOA (ID) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE MEMBROS (
    IDPROJETO BIGSERIAL NOT NULL,
    IDPESSOA BIGINT NOT NULL,
    CONSTRAINT PK_MEMBROS_PROJETO PRIMARY KEY (IDPROJETO),
    CONSTRAINT FK_MEMBROS_PESSOA
    FOREIGN KEY (IDPESSOA) REFERENCES PROJETO (ID) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT FK_PESSOA
    FOREIGN KEY (IDPESSOA) REFERENCES PESSOA (ID) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);

INSERT INTO pessoa (nome, datanascimento, cpf, funcionario) VALUES ('Mateus Silva', '1998-08-22', '999.999.999-99', TRUE);

UPDATE pessoa p SET p.nome = ?, p.datanascimento = ?, p.cpf = ?, p.funcionario = ? WHERE p.id = 1;

DELETE FROM pessoa WHERE id = ?;